### ISSUE TITLE
【开源自荐】--dperf：100Gbps开源网络性能测试仪

### ISSUE THREAD

**Issue by pengjianzhang** [OpenGithubs/monthly#6]
1).项目名称：dperf

2).项目地址：https://github.com/baidu/dperf

3).项目简介 (100 字以内)：
   dperf 是一个100Gbps的网络性能与压力测试软件。单机可以达到数千万HTTP每秒新建，数百Gbps带宽，几十亿并发。国内大厂都在用dperf测试其网卡、网络设备、四层负载均衡。知名开源四层负载均衡DPVS在用dperf做性能测试，发布性能测试报告。

4).推荐原因:
dperf是目前性能最高开源网络测试仪。

**Comment by OpenGithubs** [comment]
已加入社区推荐: https://open.itc.cn/github/dig?cateId=01GTGX6MYVBA4PFXTH4EH6P1SE&repoId=R_kgDOGkCIYQ
